---
title: "Data Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
```

```{r}
# Example for how to load a custom function from the same project
source("../R-Scripts/custom_theme.R")
```


```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

```{r}
# Calculate annual escapement by species and region of salmon
# Specifically, let's look only for Chinook, Sockeye, Chum, Coho, and Pink

annual_esc <- esc %>% 
  separate(sampleDate, #split the values in our date column
           into = c("Year", "Month", "Date"),
           sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarise(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))
```


## ggplot


```{r}

ggplot(annual_esc, mapping = aes(x = Species, y = escapement)) +
  geom_col(fill = "olivedrab4") +
  ggtitle("A Regular Ol' Bar Plot")


```
<br>

```{r}
# Let's look at a ggplot of species within the Kodiak Region
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")

my_theme <- theme_bw() +
  theme(legend.position = "bottom")


ggplot(kodiak_esc, aes(x=Year, y=escapement, color=Species)) +
  geom_point() +
  geom_line() +
  ylab("Escapement (num fish)") +
  ggtitle("Kodiak Escapement") + 
  my_theme


ggplot(kodiak_esc, aes(x=Year, y=escapement, color=Species)) +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  scale_y_continuous(labels = comma) +
  geom_line() +
  ylab("Escapement (num fish)") +
  ggtitle("Kodiak Escapement") +
  my_theme

```


## Let's create an interactive map with leaflet!

```{r include=FALSE}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r echo=FALSE}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location)
```

